[package]
name = "tl_interface"
version = "0.1.0"
edition = "2021"

authors = ["Alexander Granin <graninas@gmail.com>"]
description = "Type-level interface for type-level programming in Rust"
license = "MIT"
repository = "https://github.com/graninas/type_level"
